version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: 'alessio'
      MYSQL_PASSWORD: 'paolucci'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - 3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
